/**
 * debugger.ts — Centralized per-stage structured debug logging.
 *
 * Each pipeline stage emits structured log events with a tag, level, and data.
 * Events are stored in a ring buffer per stage. Stages can be individually
 * enabled/disabled and filtered by minimum log level.
 *
 * The ring buffer is consumed by:
 *   - Console output (real-time, filtered)
 *   - compressForLLM.ts (structured summary for LLM context)
 *   - diag.ts (BER tracking, timing, snapshots)
 *   - React debug panel (live display)
 */

// ─── Log Levels ──────────────────────────────────────

export const LOG_LEVEL = {
  DEBUG: 0,
  INFO: 1,
  WARN: 2,
  ERROR: 3,
} as const;

export type LogLevel = (typeof LOG_LEVEL)[keyof typeof LOG_LEVEL];

const LEVEL_NAMES: Record<LogLevel, string> = {
  [LOG_LEVEL.DEBUG]: 'DEBUG',
  [LOG_LEVEL.INFO]: 'INFO',
  [LOG_LEVEL.WARN]: 'WARN',
  [LOG_LEVEL.ERROR]: 'ERROR',
};

// ─── Stage Tags ──────────────────────────────────────

export const STAGE = {
  PILOT_SCAN: 'PILOT_SCAN',
  PILOT_LOCK: 'PILOT_LOCK',
  SYNC_DETECT: 'SYNC_DETECT',
  FRAME_BITS: 'FRAME_BITS',
  BLOCK_SENTINEL: 'BLOCK_SENTINEL',
  BLOCK_PROCESS: 'BLOCK_PROCESS',
  ECC_DECODE: 'ECC_DECODE',
  SQUAWK_CAL: 'SQUAWK_CAL',
  END_DETECT: 'END_DETECT',
  CHANNEL: 'CHANNEL',
  DEBUG: 'DEBUG',
} as const;

export type StageTag = (typeof STAGE)[keyof typeof STAGE];

// ─── Log Event ───────────────────────────────────────

export interface LogEvent {
  stage: StageTag;
  level: LogLevel;
  timestamp: number;
  /** Structured data — keys depend on stage */
  data: Record<string, unknown>;
  /** Human-readable summary (generated by the caller) */
  summary: string;
}

// ─── Debug Logger ────────────────────────────────────

export interface DebugLoggerConfig {
  /** Max events per stage ring buffer */
  ringBufferSize: number;
  /** Default minimum level for all stages */
  defaultLevel: LogLevel;
  /** Whether to also write to console.log */
  consoleOutput: boolean;
}

const DEFAULT_CONFIG: DebugLoggerConfig = {
  ringBufferSize: 500,
  defaultLevel: LOG_LEVEL.DEBUG,
  consoleOutput: true,
};

export class DebugLogger {
  private cfg: DebugLoggerConfig;
  /** Ring buffer per stage */
  private buffers: Map<StageTag, LogEvent[]> = new Map();
  /** Per-stage min log level */
  private stageLevels: Map<StageTag, LogLevel> = new Map();
  /** Per-stage enabled flag */
  private stageEnabled: Map<StageTag, boolean> = new Map();

  /** All events (global ring buffer for last N events regardless of stage) */
  private globalBuffer: LogEvent[] = [];
  private globalMax = 2000;

  private totalEvents = 0;

  constructor(cfg?: Partial<DebugLoggerConfig>) {
    this.cfg = { ...DEFAULT_CONFIG, ...cfg };
    // Enable all stages by default at default level
    for (const tag of Object.values(STAGE)) {
      this.stageEnabled.set(tag as StageTag, true);
      this.stageLevels.set(tag as StageTag, this.cfg.defaultLevel);
      this.buffers.set(tag as StageTag, []);
    }
  }

  /** Log an event. Returns the event for chaining. */
  log(stage: StageTag, level: LogLevel, data: Record<string, unknown>, summary?: string): LogEvent {
    this.totalEvents++;

    // Check if this stage is enabled and level is sufficient
    if (!this.stageEnabled.get(stage) && level < LOG_LEVEL.WARN) {
      // Always let WARN and ERROR through even if stage is disabled
      // Return dummy event for API consistency
      return { stage, level, timestamp: performance.now(), data, summary: summary || '' };
    }

    const minLevel = this.stageLevels.get(stage) ?? LOG_LEVEL.DEBUG;
    if (level < minLevel) {
      return { stage, level, timestamp: performance.now(), data, summary: summary || '' };
    }

    const event: LogEvent = {
      stage,
      level,
      timestamp: performance.now(),
      data,
      summary: summary || this.defaultSummary(stage, data),
    };

    // Add to stage ring buffer
    const buf = this.buffers.get(stage);
    if (buf) {
      buf.push(event);
      if (buf.length > this.cfg.ringBufferSize) buf.shift();
    }

    // Add to global ring buffer
    this.globalBuffer.push(event);
    if (this.globalBuffer.length > this.globalMax) this.globalBuffer.shift();

    // Console output
    if (this.cfg.consoleOutput && level >= LOG_LEVEL.INFO) {
      const prefix = `[${event.stage}]`;
      if (level === LOG_LEVEL.ERROR) {
        console.error(prefix, event.summary, event.data);
      } else if (level === LOG_LEVEL.WARN) {
        console.warn(prefix, event.summary, event.data);
      } else {
        console.log(prefix, event.summary);
      }
    }

    return event;
  }

  /** Convenience: log at DEBUG level */
  debug(stage: StageTag, data: Record<string, unknown>, summary?: string): LogEvent {
    return this.log(stage, LOG_LEVEL.DEBUG, data, summary);
  }

  /** Convenience: log at INFO level */
  info(stage: StageTag, data: Record<string, unknown>, summary?: string): LogEvent {
    return this.log(stage, LOG_LEVEL.INFO, data, summary);
  }

  /** Convenience: log at WARN level */
  warn(stage: StageTag, data: Record<string, unknown>, summary?: string): LogEvent {
    return this.log(stage, LOG_LEVEL.WARN, data, summary);
  }

  /** Convenience: log at ERROR level */
  error(stage: StageTag, data: Record<string, unknown>, summary?: string): LogEvent {
    return this.log(stage, LOG_LEVEL.ERROR, data, summary);
  }

  // ─── Stage Filtering ─────────────────────────────

  /** Enable or disable logging for a specific stage */
  setStageEnabled(stage: StageTag, enabled: boolean): void {
    this.stageEnabled.set(stage, enabled);
  }

  /** Set minimum log level for a stage */
  setStageLevel(stage: StageTag, level: LogLevel): void {
    this.stageLevels.set(stage, level);
  }

  /** Enable all stages */
  enableAll(): void {
    for (const tag of Object.values(STAGE)) {
      this.stageEnabled.set(tag as StageTag, true);
    }
  }

  /** Disable all non-critical stages (keep WARN/ERROR) */
  disableAll(): void {
    for (const tag of Object.values(STAGE)) {
      this.stageEnabled.set(tag as StageTag, false);
    }
  }

  // ─── Buffer Access ───────────────────────────────

  /** Get all events for a specific stage */
  getStageBuffer(stage: StageTag): readonly LogEvent[] {
    return this.buffers.get(stage) ?? [];
  }

  /** Get last N events from the global buffer */
  getGlobalBuffer(n?: number): readonly LogEvent[] {
    if (n === undefined) return this.globalBuffer;
    return this.globalBuffer.slice(-n);
  }

  /** Get all events across all stages (for compressForLLM) */
  getAllEvents(): LogEvent[] {
    const all: LogEvent[] = [];
    for (const [, buf] of this.buffers) {
      for (const e of buf) all.push(e);
    }
    // Sort by timestamp
    all.sort((a, b) => a.timestamp - b.timestamp);
    return all;
  }

  /** Get events in a time range */
  getEventsSince(timestamp: number): LogEvent[] {
    return this.globalBuffer.filter(e => e.timestamp >= timestamp);
  }

  /** Clear all buffers */
  clear(): void {
    for (const [, buf] of this.buffers) buf.length = 0;
    this.globalBuffer.length = 0;
    this.totalEvents = 0;
  }

  /** Total events logged */
  getTotalEvents(): number { return this.totalEvents; }

  /** Get stats per stage */
  getStageStats(): Record<StageTag, { count: number; lastLevel: string; lastSummary: string }> {
    const stats: any = {};
    for (const [tag, buf] of this.buffers) {
      const last = buf[buf.length - 1];
      stats[tag] = {
        count: buf.length,
        lastLevel: last ? LEVEL_NAMES[last.level] : '-',
        lastSummary: last ? last.summary : '-',
      };
    }
    return stats;
  }

  // ─── Private ─────────────────────────────────────

  private defaultSummary(stage: StageTag, data: Record<string, unknown>): string {
    // Generate a minimal one-line summary from common keys
    const parts: string[] = [];
    for (const key of ['freq', 'snr', 'confidence', 'count', 'bits', 'errors', 'drift', 'amp']) {
      if (data[key] !== undefined) {
        const v = data[key];
        if (typeof v === 'number') {
          parts.push(`${key}=${v.toFixed ? v.toFixed(2) : v}`);
        } else {
          parts.push(`${key}=${v}`);
        }
      }
    }
    return parts.join(' ') || stage;
  }
}

// ─── Singleton ───────────────────────────────────────

/** Global debug logger instance */
export const debugLogger = new DebugLogger();
